/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.record;

import javax.annotation.Nonnull;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

import static java.lang.String.format;

public record RecordExample(@Nonnull UUID id, String name, Optional<String> description) {

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    @Override
    public String toString() {
        return format("RecordExample[id=%s]", id);
    }

    @Override
    public boolean equals(Object obj) {
        return this.getClass().isInstance(obj)
                && Objects.equals(this.id(), this.getClass().cast(obj).id());
    }
}
