/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.record;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Builder;
import lombok.NonNull;

import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

import static java.lang.String.format;

@Builder
public record RecordExample(@NonNull UUID id, String name, Optional<String> description) {

    public RecordExample {
        Objects.requireNonNull(id);
    }

    public Optional<String> description() {
        return Objects.requireNonNullElseGet(description, Optional::empty);
    }

    @Override
    public int hashCode() {
        return id().hashCode();
    }

    @Override
    public String toString() {
        return format("%s[id=%s]", getClass().getSimpleName(), id());
    }

    @Override
    public boolean equals(Object obj) {
        return getClass().isInstance(obj) && Objects.equals(id(), getClass().cast(obj).id());
    }
}
