/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.record;

import lombok.Builder;

import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

import static java.lang.String.format;
import static java.util.Objects.isNull;
import static java.util.Objects.requireNonNullElseGet;

@Builder
public record RecordExample(UUID id, String name, Optional<String> description) {

    public RecordExample {
        if (isNull(id)) {
            throw new IllegalArgumentException("Id is null");
        }
    }

    public Optional<String> description() {
        return requireNonNullElseGet(description, Optional::empty);
    }

    @Override
    public int hashCode() {
        return id().hashCode();
    }

    @Override
    public String toString() {
        return format("%s[id=%s]", getClass().getSimpleName(), id());
    }

    @Override
    public boolean equals(Object obj) {
        return getClass().isInstance(obj) && Objects.equals(id(), getClass().cast(obj).id());
    }
}
