/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.record;

import org.junit.jupiter.api.Test;

import java.util.UUID;

import static java.lang.String.format;
import static java.util.Optional.empty;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class RecordExampleTest {
    @Test
    void constructorsTest() {
        final UUID id = UUID.randomUUID();
        final String name = "TestName";

        final RecordExample record = new RecordExample(id, name, null);

        assertEquals(id, record.id());
        assertEquals(name, record.name());
        assertNull(record.description());
        assertEquals(format("%s[id=%s]", RecordExample.class.getSimpleName(), id), record.toString());
        assertEquals(id.hashCode(), record.hashCode());
        assertEquals(new RecordExample(id, "", empty()), record);
    }
}
